CREATE DATABASE PROYECTOFINAL;

USE PROYECTOFINAL;

CREATE TABLE DEPARTAMENTO(
	CODIGO INTEGER,
	NOMBRE VARCHAR(50),
	PRIMARY KEY (CODIGO)
);

CREATE TABLE JORNADA(
	CODIGO INTEGER,
	NOMBRE VARCHAR(50),
	ENTRADA TIME,
	SALIDA TIME,
	PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO(
	CODIGO INTEGER,
	NOMBRE VARCHAR(100),
	CODIGO_JORDANA INTEGER,
	CODIGO_DEPARTAMENTO INTEGER,
	PRIMARY KEY (CODIGO),
	FOREIGN KEY (CODIGO_JORDANA) REFERENCES JORNADA(CODIGO),
	FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

CREATE TABLE PERMISO(
	ID INTEGER,
	CODIGO_EMPLEADO INTEGER,
	FECHA DATE,
	MOTIVO VARCHAR(255),
	PRIMARY KEY (ID),
	FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADO(CODIGO)
);

CREATE TABLE MARCAJE(
	ID INTEGER,
	CODIGO_EMPLEADO INTEGER,
	TIPO_MARCAJE VARCHAR(20),
	FECHA DATETIME
);